In [1]:
import numpy as np

In [2]:
ab = [2,4,6]

In [3]:
print(type(ab))

<class 'list'>


In [5]:
arr1= np.array(ab)
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
arr2 = np.array([2,3,5])
print(arr2)

[2 3 5]


In [9]:
arr3 = arr2-arr1
print(arr3)

[ 0 -1 -1]


In [10]:
arr4 = arr2*arr1
print(arr4)

[ 4 12 30]


In [11]:
arr5 = np.dot(arr1,arr2)
print (arr5)

46


In [22]:
arr1a = arr1[0:3:2]
print(arr1a)

[2 6]


In [28]:
arr10 = np.array([[4,5,2],[3,2,5],[6,5,6]])
print (arr10.shape)

(3, 3)


In [29]:
arr11 = np.eye(3,4)
print(arr11)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [31]:
arr12 = np.zeros([2,5])
print(arr12) 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
arr13 = np.full([2,2],4)
print(arr13)

[[4 4]
 [4 4]]


In [39]:
matr1 = np.matrix(arr13)
print(type(matr1))

<class 'numpy.matrix'>


In [40]:
matr2 = np.matrix(np.full([2,2],6))
print (matr2)
print (type(matr2))

[[6 6]
 [6 6]]
<class 'numpy.matrix'>


In [53]:
matr3 = matr1*matr2-[1,2]
print (matr3)

[[47 46]
 [47 46]]


In [55]:
print(np.sum(matr3[1]))

93


In [50]:
from numpy.linalg import inv

In [54]:
np.transpose(matr3)

matrix([[47, 47],
        [46, 46]])